### ISSUE TITLE
Elastic 

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#15]
Hey mate wondering if you can help. So my database is at 8 million now but all of a sudden I'm not seeing any new torrents on the site. I checked the scraper and appears to still be queeing torrents.

Any help much appreciated

**Comment by ghost** [comment]
well it seems i cant even flag a torrent iether. its like i cannot make changes to elastic

**Comment by Raxvis** [comment]
Can you still search on the elasticsearch node?

How is your memory and harddrive space?

**Comment by ghost** [comment]
yeah i can still search on the node. but i cannot put any new data from the scraper. or downvote or upvote a torrent. i think my HDD got full so i made some space but still same issue..
“[2018-04-01T15:10:05,089][WARN ][o.e.c.r.a.DiskThresholdMonitor] [jO8Q-ek] high disk watermark [90%] exceeded on [jO8Q-ekCTxe4AJfQcIzOcQ][jO8Q-ek][/var/lib/elasticsearch/nodes/0] free: 4.3gb[9.4%], shards will be relocated away from this node
[2018-04-01T15:10:08,798][DEBUG][o.e.a.b.TransportShardBulkAction] [torrents][3] failed to execute bulk item (update) BulkShardRequest [[torrents][3]] containing [12] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [file_media]”

**Comment by Raxvis** [comment]
That should fix it, but you probably need to restart things

**Comment by ash121121** [comment]
yeah i thought it would but still the same lol.. dam thing ill try a restore

**Comment by ghost** [comment]
this is the new errors after the restart.
path: /torrents/hash/dcf7f6c5883fa863ea040a9e9ddb6728ec908560, params: {index=torrents, id=dcf7f6c5883fa863ea040a9e9ddb6728ec908560, type=hash}
org.elasticsearch.action.NoShardAvailableActionException: No shard available for [get [torrents][hash][dcf7f6c5883fa863ea040a9e9ddb6728ec908560]: routing [null]]
	a

**Comment by Raxvis** [comment]
Your elasticsearch seems to be having some issues.  You might need a second
node or more ram

**Comment by ghost** [comment]
So I tried to recover it but did not succeed.  I did a restore from backup and all seems great now. Thanks for your help mate appreciate it.
